# @package _global_
env:
  env: ffsp
  min_processing_time: 2
  max_processing_time: 10
  id: ${env.env}-${env.num_jobs}j-${env.num_stage}s-${env.min_ma_per_stage}m


policy:
  embed_dim: 256
  num_heads: 16
  input_dropout: 0.1
  activation: gelu
  norm_first: True
  bias: True
  mask_no_edge: False  # don't! makes things worse
  param_sharing: True
  num_encoder_layers: 4
  use_context_emb: True

train:
  epochs: 100
  dataset_size: 1000
  batch_size: 1000

val:
  num_file_instances: 100
  data_dir: 
    - ${paths.test_data_dir}/ffsp/${env.num_jobs}j_${env.num_stage}s_${env.min_ma_per_stage}-${env.max_ma_per_stage}m.pt

test:
  batch_size: 1
  num_file_instances: 100
  data_dir:
    - ${paths.test_data_dir}/ffsp/${env.num_jobs}j_${env.num_stage}s_${env.min_ma_per_stage}-${env.max_ma_per_stage}m.pt